# AWS CloudFormation resources

Resources:
  PendingOrdersQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${env:PENDING_ORDER_QUEUE_NAME}

  CompletedOrdersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "orderId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "orderId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${env:COMPLETED_ORDERS_TABLE}
      StreamSpecification:
        StreamViewType: NEW_IMAGE
